name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Weekly scan

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit safety
          
      - name: Run Bandit
        run: bandit -r . -x ./tests,./venv,./node_modules
        
      - name: Run Safety
        run: safety check
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install npm dependencies
        run: npm ci || npm install
        
      - name: Run npm audit
        run: npm audit --audit-level=high || true
        
      - name: Check anima_ui dependencies
        run: |
          cd anima_ui
          npm ci || npm install
          npm audit --audit-level=high || true
          
      - name: Check soulcore-gui dependencies
        run: |
          cd soulcore-gui
          npm ci || npm install
          npm audit --audit-level=high || true
